### ISSUE TITLE
Can not delete entries with the Apple News plugin enabled.

### ISSUE THREAD

**Issue by jwrudzin** [craftcms/apple-news#11]
I’m building a site that uses the Apple News plugin, and for some reason when I try to delete an entry I’m running into an error (see attached screenshot). It appears that this error is related to the Apple News plugin, because when I disable the plugin I can delete entries without issue. This error occurs both when I try to delete an entry in the CMS, as well as when I try to delete an entry via php in a module.
![Screen Shot 2020-01-31 at 6 00 22 PM](https://user-images.githubusercontent.com/18213990/74752228-5b35f680-523c-11ea-953e-1fedb510f314.png)

**Comment by brandonkelly** [comment]
Just released Apple News 2.0.1 with a fix for this.
