### ISSUE TITLE
Make connection timeout configurable

### ISSUE THREAD

**Issue by frsharpe** [craftcms/apple-news#13]
### Description

When saving / updating articles, we routinely run into the following error:

```
Array
(
    [code] => 28
    [message] => Operation timed out after 30000 milliseconds with 0 bytes received
    [response] => 
)
 in /app/vendor/chapter-three/apple-news-api/src/PublisherAPI/Base.php on line 197
```

When this issue occurs, often times the article is created on the Apple News side - but none of the meta data makes it back into Craft - creating 'disconnected' Apple News entries.  We address this by manually pulling the meta data from apple news and updating the database.

I concede that this could be from our content (which tends to be long / rich), or our article class implementation.  But maybe others see this issue as well?

It would be great if we could configure the timeout for the connection, (adding say another option in the config files) to allow for a longer timeout for publishers like us.

**Comment by angrybrad** [comment]
Added in 3.0.0
